### PR TITLE
Chart for requests (REQUIRES #52)

### PR DESCRIPTION
**Pull request by Ycirn**
This requires #52

### CODE REVIEW

**Comment by ajax-lives** [comment]
Needs conflict fixes - then will merge.

**Comment by naslundx** [comment]
I would advise against including minified code in this way, it undermines the trustworthiness of the site. In general having too many features means more code which means harder to verify it does what it says it should.

**Comment by ajax-lives** [comment]
There is no site, its ran from source, or the Github page.
Any minification via the old site was done by Cloudflare.

**Comment by ajax-lives** [comment]
@Ycirn has some conflicts after @naslundx merges.

**Comment by naslundx** [comment]
> Any minification via the old site was done by Cloudflare.

There is literally minified code in this PR.

**Comment by Ycirn** [comment]
> > Any minification via the old site was done by Cloudflare.
> 
> There is literally minified code in this PR.

I can unminify it but its a huge blob of javascript that wont ever get changed

**Comment by Ycirn** [comment]
I'll fix this entire PR up and uminifying the code after #52 gets pushed

**Pull request closed without merging**
