### PR TITLE
Improved index.html and added https protocol to a url

### PR DESCRIPTION
**Pull request by Itroublve**

### CODE REVIEW

**Review by Itroublve — COMMENTED** [review]
Unnecessary code which is still written and created by the JS code. This way there's only the need to add Url's and no need to modify the rest of the code.

**Comment by Ycirn** [comment]
This will remove the stats though, I'm unsure this is something we want.

**Comment by Itroublve** [comment]
> Wait the JS makes it appear aswell?

Yes, cuz it's rewriting what's there by default on start. So it's just code wasted unless ofc if javascript is disabled, but then what's the point of showing any stats.

**Comment by Ycirn** [comment]
> > Wait the JS makes it appear aswell?
> 
> Yes, cuz it's rewriting what's there by default on start. So it's just code wasted unless ofc if javascript is disabled, but then what's the point of showing any stats.

The stats dont show on my end when i remove that part of the code

**Comment by Itroublve** [comment]
> > > Wait the JS makes it appear aswell?
> > 
> > 
> > Yes, cuz it's rewriting what's there by default on start. So it's just code wasted unless ofc if javascript is disabled, but then what's the point of showing any stats.
> 
> The stats dont show on my end when i remove that part of the code

That's weird. I'll check.

**Comment by Itroublve** [comment]
```       var statsEl = document.getElementById('stats');
        function printStats() {
            statsEl.innerHTML = '<pre>' + JSON.stringify(targets, null, 2) + '</pre>'
        }
        setInterval(printStats, 100);
```
https://github.com/ajax-lives/NoRussian/blob/78305b51955dd89249d09049dd8678bba2155a06/index.html#L1259

As you may be able to see, the printStats is being called in a 100ms interval and everytime it is called the innerHTML is rewritten. So I'm not sure why you don't get the stats to show up.

**Comment by Ycirn** [comment]
check ur discord dm

**Comment by Ycirn** [comment]
This works, the issue was on my end. Adding this will save me like 15 min trying to add 100 sites again.

**Comment by ajax-lives** [comment]
Awesome work!  Thanks!

**Pull request merged**
