### PR TITLE
Counter for total requests made

### PR DESCRIPTION
**Pull request by naslundx**
Thought this would be nice to see.

### CODE REVIEW

**Review by MadKamel — APPROVED** [review]
Just tested it out, this is a really great addition. It's nice to have a solid number of requests. As a nitpick, it could do with a total number of dropped requests.

**Review by MadKamel — APPROVED** [review]
Useful feature, nice to check in to see the total number of errored requests alongside the total request count. Nice feature! I think this is merge-ready.

**Comment by naslundx** [comment]
Great :)

**Comment by Ycirn** [comment]
Good little extra, I'd say add it.

**Comment by ajax-lives** [comment]
So many PRs, all 3 will need updating.  Sorry about that!  Will merge ASAP after.

**Comment by naslundx** [comment]
Updated!

**Review by Ycirn — CHANGES_REQUESTED** [review]
Broken, total counter says have I have made 600+ requests while everything added up gives me less than 300. The counter is looping somewhere it seems (or its the individual target counter that is broken?)

**Comment by naslundx** [comment]
@Ycirn Interesting, does this happen every time? I just tried running it myself, the total counter says 615 and summing every category up with

`sum=0; for (var c of document.querySelectorAll("td.requests")) sum += parseInt(c.innerText); console.log(sum)`

also gives me 615.

(it might be a random/timing error fixed in #65 )

**Comment by Ycirn** [comment]
image
This is what happens every time, I've only ran it in Firefox though

**Comment by naslundx** [comment]
@Ycirn Not sure what to make of the screenshot since it's not the full page, there should be 200+ URLs in that grid? If the rest of them also average 8-10 requests that should sum up to around 200 * 9 = 1800 requests. How are you doing the counting?

**Comment by Ycirn** [comment]
Ah wait I made a mistake in my own calculating function, it actually works. My bad, sorry. 

Good change, add it. Will make a small chart for this counter.

**Comment by Ycirn** [comment]
Hey @naslundx I'm trying to make my chart work with your total counter code, but it doesn't seem to work. It can't obtain the total data. Mind taking a look? (It works when I make new vars and assign them a value).

https://pastebin.com/7ST7Pktc

**Comment by naslundx** [comment]
Updated @ajax-lives

**Comment by naslundx** [comment]
What was the point of this if you just remove it with #77 ?

**Comment by ajax-lives** [comment]
Reverted.  Wasn't done on purpose.

**Pull request merged**
