### PR TITLE
Better site for the leave button

### PR DESCRIPTION
**Pull request by Ycirn**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
This is pretty great. Perfect for supporting the cause, but what about an article about the Russian media censorship and propaganda?

**Comment by Ycirn** [comment]
> This is pretty great. Perfect for supporting the cause, but what about an article about the Russian media censorship and propaganda?

I can add a "why" or "more info" button in a later PR

**Comment by MadKamel** [comment]
Nice idea, you should do that before merge.

**Comment by ajax-lives** [comment]
Will wait for @Ycirn to update that :D

**Pull request closed without merging**
