### PR TITLE
refactor and make mobile friendly

### PR DESCRIPTION
**Pull request by hoganrd**
index.html has been split into three files separating the code from the css and target list.  Used bootstrap to make more mobile friendly and cleaned up typography.  Added pause/resume button

### CODE REVIEW

**Comment by Ycirn** [comment]
Not a big fan of separating the files again

**Comment by hoganrd** [comment]
UI look is better. Don't really care if one file or three. It was just easier for me to modify that way.  Up to the maintainer.

**Comment by MadKamel** [comment]
I think that ultimately the best thing about this project is how easy it is to plant on typical computers, and having to use and download several files at once undermines this.

**Comment by Ycirn** [comment]
I'd say implement the HTML/CSS/Bootstrap changes, and implement the other guys JS part of the thing I commented. Keep the single file structure.

**Comment by hoganrd** [comment]
Bowing to the will of the people, here is a single file version.

**Comment by Bismuth-333** [comment]
Did some testing and this version uses roughly under double the CPU usage of the original file on PC 

Settings used:
- CONCURRENCY_LIMIT: 1000
- interval of printStats: 1000ms
- timeout: 1000ms

**Comment by ajax-lives** [comment]
Will test in another branch - not to worry :D
Think it's a nice improvement.

**Pull request merged**
