### PR TITLE
Complete Overhaul

### PR DESCRIPTION
**Pull request by Bismuth-333**
Added:
- More websites
- Displays total stats (requests sent and errors received)

Changed:
- Visible content (HTML and CSS)
- JavaScript

### CODE REVIEW

**Comment by MadKamel** [comment]
I can't see any benefits to accepting this? What does this add, specifically? (Of course, apart from the new websites to target.)

**Comment by Bismuth-333** [comment]
Just wanted to make it look nicer

**Comment by Ycirn** [comment]
the javascript part that removes the number_of_requests bla bla after ever site is nice, haven't tested if it works though.

**Comment by Bismuth-333** [comment]
The rand thing was a leftover bit that I was testing and forgot to remove, no point to it really

**Comment by ajax-lives** [comment]
This looks great!  Unfortunately - another PR made, conflicts with it - if you can refactor it to resolve the new conflicts, I can merge it.

**Comment by Bismuth-333** [comment]
First time using bootstrap, so it took a bit

Changed
- Page styling
- Stats to a table, easier to read

Removed
- Array randomization, too costly on the CPU (and a bit unnecessary)

**Comment by Bismuth-333** [comment]
Added settings panel for:
- Stats update interval (able to completely disable stat updates)
- Concurrency limit
- Fetch timeout

**Comment by Ycirn** [comment]
I like how many changes you tried to add, even though non have made it so far. I don't feel like rewriting everything would be useful again, but, that last option. Put it in with the current code base, and make it behind an "advanced" button thats next to the pause/resume button. This button should open a modal that lets you tweak the settings yourself

`    <div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Warning!</h5>
            </div>
            <div class="modal-body">
              <p>The action of DoSing or participating in DDoS is still illegal. Click on continue if you wish to support Ukraine in taking down Russian and Belarussian propaganda news, government, military and banking sites.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" onclick="window.location.href='https://www.google.com'">Leave</button>
              <button type="button" class="btn btn-primary" data-dismiss="exampleModalLabel" onclick="togglePause(); myModal.toggle();">Continue</button>
            </div>
          </div>
        </div>
      </div>`
      
      `var myModal = new bootstrap.Modal(document.getElementById('exampleModal'), {})
        myModal.toggle();`
        
        `button onclick='myModal.toggle();'`
        
        Since ur new with bootstrap, you can use this bootstrap code to make a modal/popup work.

**Pull request closed without merging**
