### PR TITLE
Add Embassy URLs and 404 timeout

### PR DESCRIPTION
**Pull request by anonuser6412**
Added embassy URLs
UI changes (lower power & easier on eyes)
Minor text changes to make the site more friendly to passerby eyes.

Added 404 timeout feature - if we get 100% 404s, we wait for minutes instead of spamming the dead URL.

Slava Ukraini

### CODE REVIEW

**Comment by ajax-lives** [comment]
Looks very nice!  My only gripe is the removal of the warning popup, if you can factor that in - its a guaranteed merge :D

**Comment by anonuser6412** [comment]
> Looks very nice! My only gripe is the removal of the warning popup, if you can factor that in - its a guaranteed merge :D

Done!
It wasn't showing up on my browser when run locally, so I missed it. Thanks!

**Comment by ajax-lives** [comment]
Merged!  Very cool!  Thanks for your hard work <3

**Comment by anonuser6412** [comment]
I also adapted the program to run in the background on windows computers using batch.
Please feel free to look at the repository

https://github.com/anonuser6412/hummingbird

**Pull request merged**
